# 基本
use_frameworks!
platform :ios, ‘9.0’

source 'https://github.com/CocoaPods/Specs.git'

target 'EasyWeather' do

# 网络库
pod 'Alamofire', '~> 3.4'

# Sqlite操作
pod 'SQLite.swift', '~> 0.10.1' 

# Json
pod 'SwiftyJSON'

# 布局
pod 'SnapKit', '~> 0.15.0'

end
